# Generated by Django 3.2.3 on 2021-05-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0007_auto_20210520_1522'),
        ('rareapi', '0007_auto_20210520_1849'),
        ('rareapi', '0007_auto_20210520_1907'),
        ('rareapi', '0007_auto_20210520_2007'),
    ]

    operations = [
    ]
